config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'items#index'

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'users_unsubscribe'

  get 'items/search', to: 'items#search', as: 'search_items'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch 'user_status' # ユーザーステータスの更新
    end
  end

  resources :items, only: [:index, :show] do
    resource :favorite_items, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :tags, only: [:index, :create, :edit, :update, :destroy]

  resources :reviews do
    resource :favorite_reviews, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true

  GUEST_USER_EMAIL = "guest@example.com"
  
  #ゲストユーザー
  def self.guest
    user = find_or_initialize_by(email: GUEST_USER_EMAIL)
    if user.new_record?  # まだ保存されていない新しいレコードの場合
      user.password = SecureRandom.urlsafe_base64
      user.name ||= "guest_user"  # ユーザー名が未設定の場合のみデフォルト値を設定
      user.save!
    end
    user
  end

  has_many :reviews
  has_many :favorite_reviews, dependent: :destroy
  has_many :favorite_items, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  # 無効なユーザーアカウントはログインできないようにする
  def active_for_authentication?
    super && is_active?
  end
  
  # 無効なユーザーアカウントにエラーメッセージを表示しない
  def inactive_message
    is_active? ? super : :account_inactive
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_items = @user.favorite_items.includes(:item)
    @favorite_reviews = @user.favorite_reviews.includes(:review)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(is_active: true)
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'ユーザー情報が更新されました。'
    else
      render :edit
    end
  end  

  def unsubscribe
    @user = User.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_active: false)
    reset_session
    redirect_to root_path, notice: "退会処理を実行いたしました"
  end
  
  def user_status
    @user = User.find(params[:id])
    @user.update(is_active: !@user.is_active)
    redirect_to users_path, notice: "ユーザーのステータスを更新しました。"
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
    <h3 class="mb-0">ユーザー一覧</h3>
      <table class = "table table-hover table-inverse m-3">
        <thead class="table-active">
          <th class="col-3">ユーザー名</th>
          <th class="col-3">メールアドレス</th>
          <th class="col-2">レビュー数</th>
          <th class="col-2">いいね数</th>
          <th class="col-2">ステータス</th>
          <th></th>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.reviews.count %></td>
          <td>
            <%= user.reviews.sum(&:favorite_reviews_count) %>
          </td>
          <td>
            <% if user.is_active == true %>
              有効
            <% else %>
              退会済み
            <% end %>
          </td>
          <td><%= button_to "ステータス変更", user_status_user_path(user), method: :patch, class: 'btn btn-primary' %></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 px-0 mx-auto">
      <h3 class="mb-0">ユーザー情報編集</h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 bg-white p-5 mx-auto rounded-lg">
      <%= form_with model: @user, url: user_path(current_user), method: :patch do |f| %>
        <div class="mb-4">
          <label for="user_name">ユーザー名</label>
          <%= f.text_field :name, class: "form-control", autofocus: true, autocomplete: "name" %>
        </div>

        <div class="mb-4">
          <label for="user_email">メールアドレス</label>
          <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="d-flex justify-content-between">
          <%= f.submit "編集内容を保存", class: "btn btn-success" %>
          <%= link_to "退会する", users_unsubscribe_path(@user), method: :delete, data: { confirm: "本当に退会しますか？" }, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>

  <div class="row">
    <div class="col">
      <%= render 'users/user' %>      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="p-4 border rounded">
        <h4 class="mb-4 d-flex justify-content-between align-items-center">ユーザー情報
          <% if @user.id == current_user.id %>
            <%= link_to "編集する", edit_user_path(current_user), class: "btn btn-success" %>
          <% end %>
        </h4>

        <table class="table">
          <tbody>
            <tr>
              <th style="width: 150px;">氏名</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th style="width: 150px;">レビュー数</th>
              <td><%= @user.reviews.count %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <h4>レビュー履歴</h4>
    <%= render 'reviews/review_index', reviews: @reviews %>
  </div>
  
  <div class="row mt-5">
    <h4>いいねしたレビュー</h4>
    <%= render 'favorite_reviews/favorite_review', favorite_reviews: @favorite_reviews %>
  </div> 

  <div class="row mt-5">
    <h4>いいねしたアイテム</h4>
    <%= render 'favorite_items/favorite_item', favorite_items: @favorite_items %>
  </div> 
  
</div>