config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'items#index'

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'users_unsubscribe'

  get 'items/search', to: 'items#search', as: 'search_items'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch 'user_status' # ユーザーステータスの更新
    end
  end

  resources :items, only: [:index, :show] do
    resource :favorite_items, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :tags, only: [:index, :create, :edit, :update, :destroy]

  resources :reviews do
    resource :favorite_reviews, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :reviews
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :tags
  has_many :favorite_items, dependent: :destroy
  
  # 特定のユーザーがアイテムをお気に入りにしているかどうかを確認するメソッド  
  def favorited_item_by?(user)
    favorite_items.where(user_id: user.id).exists?
  end
  
  # お気に入りのレビューの数を返すメソッド
  def favorite_items_count
    favorite_reviews.count
  end
  
  # 価格の降順でアイテムを並べ替えるスコープ
  scope :price_desc, -> {order(price: :desc)}
  
  # 価格の昇順でアイテムを並べ替えるスコープ
  scope :price_asc, -> {order(price: :asc)} 
  
  # いいねの数でアイテムを並べ替えるスコープ
  scope :favorite_items_count, -> { order(favorite_items_count: :desc) }
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_default_genre_id, only: [:search]
  
  # トップページ
  def index
    @reviews = Review.latest.limit(3)
    @favorite_items = FavoriteItem.recently_favorited_items(3)
  end
  
  # 商品詳細表示ページ
  def show
    @item = Item.find(params[:id])
    @review = Review.new
    @reviews = @item.reviews
  end

  # 商品検索アクション
  def search
    #空の配列を代入
    @items = []
    @keyword = params[:keyword]
    @genre_ids = params[:genre_ids] || []
    @tag_ids = params[:tag_ids] || []

    if @keyword.present? || @genre_ids.present? || @tag_ids.present?
      # APIで取得したデータを格納する
      results = RakutenWebService::Ichiba::Item.search(search_params)

      # itemsに取得データを格納する
      results.each do |result|
         # 名前で検索。もし見つからない場合は、新しいアイテムを初期化します。
        item = Item.find_or_initialize_by(name: result["itemName"])
        item.attributes = read(result)
        item.save
        @items << item
      end
    end
    # 検索条件をビューに渡す
  @search_conditions = {
    keyword: @keyword,
    genre_ids: @genre_ids,
    tag_ids: @tag_ids
  }  
  end

  private

  # APIから取得したデータをモデル用のデータに変換する
  def read(result)
    name = result["itemName"]
    shop_code = result["shopCode"]
    price = result["itemPrice"]
    genre_id = result["genreId"]
    rakuten_url = result["itemUrl"]
    image_url = result["mediumImageUrls"]
    caption = result["itemCaption"]
    {
      name: name,
      shop_code: shop_code,
      price: price,
      genre_id: genre_id,
      rakuten_url: rakuten_url,
      image_url: image_url,
      caption: caption,
    }
  end
  
  # genreId のデフォルト値を設定
  def set_default_genre_id
    @genre_ids ||= ["567167"] if @genre_ids.blank?
  end


  # API検索用のパラメータを組み立てる
  def search_params
    search_conditions = {}
  
    # keyword の条件
    if @keyword.present?
      search_conditions[:keyword] = "#{@keyword} #{tag_keywords}"
    elsif @tag_ids.present?
      # keyword がなくても tag だけが選択されている場合、tag_keywords を利用する
      search_conditions[:keyword] = tag_keywords
    end

    # genreId の条件
    if @genre_ids.present? && @genre_ids.first != "0"
      search_conditions[:genreId] = @genre_ids.join(",")
    elsif @keyword.present?
      # キーワードのみで検索した場合、genreId を固定する
      @genre_ids = ["567167"]
      search_conditions[:genreId] = @genre_ids.join(",")
    end
    
    #戻り値
    search_conditions
  end

  # タグのキーワードを取得
  def tag_keywords
    Tag.where(id: @tag_ids).pluck(:name).join(" ")
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <!--<p>-->
      <!--  |<%= link_to '値段が高い順', search_items_path(price_desc: "true") %>-->
      <!--  |<%= link_to '値段が安い順', search_items_path(price_asc: "true") %>-->
      <!--  |<%= link_to 'いいねの多い順', search_items_path(favorite_items_count: "true") %>-->
      <!--</p>-->
      <table class="table">
        <thead>
          <th class="">商品画像</th>
          <th class="">製品名</th>
          <th class="">値段</th>
          <th class="col-2">いいね数</th>
        </thead>
        <% @items.first(10).each do |item| %>
        <tbody>
          <td>
            <% if item.image_url.present? %>
              <%= link_to item_path(item) do %>
                <% images = JSON.parse(item.image_url) %>
                <% if images.present? && images.first.present? %>
                  <%= image_tag images.first %>
                <% else %>
                  <!-- 画像が存在しない場合の処理 -->
                  <%= image_tag "no_image.jpg" %>
                <% end %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to item.name, item_path(item) %></td>
          <td><%= number_with_delimiter(item.price) %>円</td>
          <td style="text-align: center;">♡<%= item.favorite_items.count %></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/items/_modal.html.erb
<button type="button" class="btn btn-success" style="width: 100%" data-toggle="modal" data-target="#exampleModal">
  Introduction
</button>

<!-- モーダル本体 -->
<div class="modal fade show" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Introduction</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- ここに機能の説明を書く -->
        <h5>GAME JOYへようこそ！</h5>
        <br>
        キーワード(製品名等)を記入<br>
        または、<br>
        キーワードタグ、ジャンルを選択して、みたい商品を検索！<br>
        <br>
        ゲーミングデバイスの情報を確認しよう！<br>
        レビュー投稿も待ってます！<br>
        <br>
        ※商品情報は楽天市場API(楽天Webサービス)を<br>
        活用させていただいています。
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/items/_search_genre.html.erb
<div class="container mt-4">
  <div class="col-12 my-4">
    <%= render 'items/modal' %>
  </div>

  <div class="row justify-content-center">
    <%= form_with url: search_items_path, method: :get, local: true do |f| %>

      <div class="col-12 mb-4">
        <strong>キーワードを入力</strong>
        <%= f.text_field :keyword, placeholder: "入力欄", value: params[:keyword], class: "form-control mx-auto mt-2" %>
      </div>

      <div class="col-12 mb-4">
        <strong>キーワード一覧</strong>

        <div style="margin-top: 5px;">
          <button type="button" id="toggleKeywords" style="padding: 5px; color: #000; border: 1px solid #000; cursor: pointer; border-radius: 5px; font-size: 14px; width: 100%">キーワード表示切り替え</button>
        </div>

        <table class="table mt-2">
          <tbody>
            <% Tag.all.each do |tag| %>
              <tr hidden>
                <td>
                  <%= check_box_tag "tag_ids[]", tag.id, params[:tag_ids].present? ? params[:tag_ids].include?(tag.id.to_s) : false, id: "tag_#{tag.id}" %>
                </td>
                <td>
                  <%= label_tag "tag_#{tag.id}", tag.name %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-12">
        <strong>ジャンル一覧</strong>

        <table class="table mt-2">
          <tbody>
            <% Genre.all.each do |genre| %>
              <tr>
                <td>
                 <%= radio_button_tag "genre_ids[]", genre.id, params[:genre_ids].present? ? params[:genre_ids].include?(genre.id.to_s) : false, id: "genre_#{genre.id}" %>
                </td>
                <td>
                  <%= label_tag "genre_#{genre.id}", genre.name %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <button type="button" onclick="formSubmit()" class="btn btn-primary" style="width: 100%;">Search</button>
      <% end %>
    </div>
  </div>
</div>

<script>
  function formSubmit() {
    document.querySelector('form').submit();
  }

  document.addEventListener('turbolinks:load', function() {

    var toggleKeywordsButton = document.getElementById('toggleKeywords');
    var keywordsTable = document.querySelector('.table');

    if (toggleKeywordsButton && keywordsTable) {
      toggleKeywordsButton.addEventListener('click', function(event) {
        event.preventDefault();

        var rows = keywordsTable.querySelectorAll('tbody tr');
        rows.forEach(function(row) {
          row.hidden = !row.hidden;
        });
      });
    }
  });

</script>

app/views/items/_static_rate.html.erb
<div id="show_star-<%= review.id %>"></div>
<script>
    var elem = document.querySelector('#show_star-<%= review.id %>');
    var opt = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        readOnly: true,
        half: true, 
        score: <%= review.star %>
    };
    raty(elem,opt);
</script>

app/views/items/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-8">
    <h3>商品詳細</h3>

    <div class="card mb-3 mt-4">
      <div class="row g-0">
        <div class="col-md-4 m-3">
            <%= link_to item_path(@item) do %>
              <% images = JSON.parse(@item.image_url) %>
              <%= image_tag images.first, style: "width: 100%;" %>
            <% end %>
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title"><%= @item.name %></h5>
            <h5 class="card-text mt-5"><%= @item.price.to_s(:delimited) %>円</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4">
      <%= link_to "#", class: "btn btn-primary", data: { toggle: "collapse", target: "#captionCollapse" } do %>
        説明を読む
      <% end %>
    </div>
    <div class="collapse" id="captionCollapse">
      <small><%= @item.caption %></small>
    </div>

    <%= form_with model: @review do |f| %>

      <h4>レビュー</h4>
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.text_area :comment, rows: 5, style: "width: 100%; border: 1px solid #ddd; outline: none;" %>

      <div class="form-group position-static">
          <p>評価:</P>
          <div id="post_raty"></div> <!-- 星を出力するセレクタ -->
          <% if @review.id.nil? %> <!-- 新規投稿か判別 -->
            <script>
                var elem = document.querySelector('#post_raty');
                var opt = {
                    starOn: "<%= asset_path('star-on.png') %>",
                    starOff: "<%= asset_path('star-off.png') %>",
                    scoreName: 'review[star]',
                };
                raty(elem,opt);
            </script>
          <% else %>
            <%= render "output_star", book: book %>
          <% end %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary', style: 'background-color: #3498db; color: #fff;' %>

    <% end %>

    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="row justify-content-center">

    <div class="col-md-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-8 my-4">
      <div class="m-0 p-0">
        <!-- 背景写真 -->
        <%= image_tag asset_path('top.jpg'), alt: 'Background Image', class: 'background-image' %>
      </div>

      <h5 class="mt-4">最近投稿されたレビュー</h5>

      <div class="row">
        <% @reviews.each do |review| %>
          <div class="col-md-4 card" style="">
            <div class="card-img-top text-center p-3">
              <%= link_to review_path(review) do %>
                <% images = JSON.parse(review.item.image_url) %>
                <%= image_tag images.first %>
              <% end %>
            </div>
            <div class="card-body">
              <p class="card-text multiline-ellipsis">
                <%= review.item.name %>
              </p>
              <%= link_to "レビュー詳細", review_path(review) %>
            </div>
          </div>
        <% end %>
      </div>

      <h5 class="mt-4">最近いいねされた商品</h5>
      <div class="row">
        <% @favorite_items.each do |item| %>
          <div class="col-md-4 card" style="">
            <div class="card-img-top text-center p-3">
              <%= link_to item_path(item) do %>
                <% images = JSON.parse(item.image_url) %>
                <%= image_tag images.first %>
              <% end %>
            </div>
            <div class="card-body">
              <p class="card-text multiline-ellipsis">
                <%= item.name %>
              </p>
              <%= link_to "商品詳細", item_path(item) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>


  </div>
</div>

app/views/items/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-8 mt-4">
      <h4>検索結果</h4>

      <% if @search_conditions.present? %>
        <p>検索条件:
          <!--空の配列を定義-->
          <% conditions = [] %>
          <!--search_conditions 内に :keyword が存在する場合、検索キーワードを conditions 配列に追加-->
          <% conditions << "キーワード: #{@search_conditions[:keyword]}" if @search_conditions[:keyword].present? %>
          <!--search_conditions 内に :genre_ids が存在する場合、対応するジャンルの名前を取得してconditions 配列に追加-->
          <% conditions << "ジャンル: #{Genre.where(id: @search_conditions[:genre_ids]).pluck(:name).join(", ")}" if @search_conditions[:genre_ids].present? %>
          <!--search_conditions 内に :tag_ids が存在する場合、対応するタグの名前を取得してconditions 配列に追加-->
          <% conditions << "タグ: #{Tag.where(id: @search_conditions[:tag_ids]).pluck(:name).join(", ")}" if @search_conditions[:tag_ids].present? %>
          <!--最後に conditions 配列を文字列に変換し、それを () で囲んで表示。各条件が , で区切り-->
          <%= "(#{conditions.join('、')})" %>
        </p>
      <% end %>

      <% if @items.present? %>
        <%= render 'items/item', items: @items %>
      <% else %>
        <p>検索条件に該当する商品はありませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-8">
    <h3>商品詳細</h3>

    <div class="card mb-3 mt-4">
      <div class="row g-0">
        <div class="col-md-4 m-3">
            <%= link_to item_path(@item) do %>
              <% images = JSON.parse(@item.image_url) %>
              <%= image_tag images.first, style: "width: 100%;" %>
            <% end %>
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title"><%= @item.name %></h5>
            <h5 class="card-text my-5"><%= @item.price.to_s(:delimited) %>円</h5>
            <div class=<%= "favorite-" + @item.id.to_s %> >
              <%= render "favorite_items/btn", item: @item %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4">
      <%= link_to "#", class: "btn btn-primary", data: { toggle: "collapse", target: "#captionCollapse" } do %>
        説明を読む
      <% end %>
    </div>
    <div class="collapse" id="captionCollapse">
      <small><%= @item.caption %></small>
    </div>

    <%= form_with model: @review do |f| %>
      <div class="mt-4">
        <h4>レビュー</h4>
        <%= f.hidden_field :item_id, value: @item.id %>
        <%= f.text_area :comment, rows: 3, placeholder: "(例)エイムがよくなりました！", style: "width: 100%; border: 1px solid #ddd; outline: none;" %>

        <div class="form-group position-static">
            <div id="post_raty"></div> <!-- 星を出力するセレクタ -->
            <% if @review.id.nil? %> <!-- 新規投稿か判別 -->
              <script>
                  var elem = document.querySelector('#post_raty');
                  var opt = {
                      starOn: "<%= asset_path('star-on.png') %>",
                      starOff: "<%= asset_path('star-off.png') %>",
                      starHalf: "<%= asset_path('star-half.png') %>",
                      scoreName: 'review[star]',
                      half: true,
                  };
                  raty(elem,opt);
              </script>
            <% else %>
              <%= render "output_star", item: item %>
            <% end %>
        </div>
      </div>
      <%= f.submit '　投稿　', class: 'btn btn-primary', style: 'color: #fff;' %>

    <% end %>

    </div>
  </div>
</div>