config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'items#index'

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'users_unsubscribe'

  get 'items/search', to: 'items#search', as: 'search_items'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch 'user_status' # ユーザーステータスの更新
    end
  end

  resources :items, only: [:index, :show] do
    resource :favorite_items, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :tags, only: [:index, :create, :edit, :update, :destroy]

  resources :reviews do
    resource :favorite_reviews, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @review.user = current_user

    if @review.save
      # 成功時の処理...
      redirect_to review_path(@review), notice: 'レビューが投稿されました'
    else
      # エラー時の処理...
      flash.now[:alert] = '入力エラーがあります。'
      @item = Item.find(params[:review][:item_id])
      render 'items/show'
    end
  end


  def index
    @reviews = Review.where(is_active: true, users: { is_active: true }).includes(:user)
    
    # ソートオプション
    if params[:latest]
      @reviews = @reviews.latest
    elsif params[:old]
      @reviews = @reviews.old
    elsif params[:star_count]
      @reviews = @reviews.star_count
    elsif params[:favorite_reviews_count]
      @reviews = @reviews.favorite_reviews_count  
    else
      @reviews
    end
    
    # キーワード検索がある場合、アイテム名で一覧を絞り込む
    if params[:search_word].present?
      @reviews = @reviews.joins(:item).where("items.name LIKE ?", "%#{params[:search_word]}%")
    end
    render 'reviews/index'    
    
  end

  def show
    @review = Review.find(params[:id])
    @review_comments = @review.review_comments.joins(:user).where(users: { is_active: true })
    @review_comment = ReviewComment.new
  end

  def edit
    @review = Review.find(params[:id])
    @review_comments = @review.review_comments.joins(:user).where(users: { is_active: true })
    @review_comment = ReviewComment.new
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      # 成功時の処理...
      redirect_to review_path(@review), notice: 'レビューが更新されました'
    else
      # エラー時の処理...
      flash.now[:alert] = '入力エラーがあります。'
      render 'reviews/show'
    end    
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      # 成功時の処理...
      redirect_to reviews_path, notice: 'レビューが削除されました'
    else
      # エラー時の処理...
      flash.now[:alert] = 'エラーがあります。'
      render 'reviews'
    end    
  end

private
  def review_params
    params.require(:review).permit(:item_id, :user_id, :comment, :star, :is_active)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review_comment.html.erb
<div class="row">
  <div class="col">
    <% if current_user.id != review.user_id %>
      <%= form_with model: [review, review_comment] do |f| %>
        <%= f.text_area :content, rows:'3', placeholder: "レビューに対するコメントをご記入ください", class:"form-control"  %>
        <%= f.submit "コメント登録", class: "btn btn-primary mt-3 mb-3" %>
      <% end %>
    <% end %>
  </div>
</div>

<h5 class="mt-4">コメント一覧</h5>

<div class="row">
  <% review_comments.each do |review_comment| %>
    <div class="col-6 mt-3" style="word-wrap: break-word;">
      <%= review_comment.content %>
    </div>
    <div class="col-4 mt-3" style="word-wrap: break-word;">
      by_<%= link_to review_comment.user.name, user_path(review_comment.user) %>
    </div>
    <div class="col-2 mt-3">
      <% if current_user.id == review_comment.user_id || current_user.admin? %>
        <%= link_to "削除する", review_review_comment_path(review_comment.review, review_comment), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger" %></td>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reviews/_review_index.html.erb
<table class="table mt-4">
  <thead>
    <th class="col-1" style="text-align: center;">商品画像</th>
    <th class="col-5" style="text-align: center;">商品名</th>
    <th class="col-2" style="text-align: center;">☆レビュー</th>
    <th class="col-2" style="text-align: center;">コメント</th>
    <th class="col-2" style="text-align: center;">いいね数</th>
  </thead>
  <% reviews.each do |review| %>
  <tbody>
      <td>
        <%= link_to review_path(review) do %>
          <% images = JSON.parse(review.item.image_url) %>
          <%= image_tag images.first %>
        <% end %>
      </td>
      <td style="text-align: center;">
        <% if review.user == current_user %>
          <%= link_to review.item.name, edit_review_path(review) %>
        <% else %>
          <%= link_to review.item.name, review_path(review) %>
        <% end %>
      </td>
      <td style="text-align: center;">☆<%= review.star %></td>
      <td><%= review.comment %></td>
      <td style="text-align: center;">♡<%= review.favorite_reviews_count %></td>
  </tbody>
  <% end %>
</table>

app/views/reviews/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-8">
    <h3>レビュー詳細</h3>

    <div class="card mb-3 mt-4">
      <div class="row g-0">
        <div class="col-md-4 m-3">
            <%= link_to item_path(@review) do %>
              <% images = JSON.parse(@review.item.image_url) %>
              <%= image_tag images.first, style: "width: 100%;" %>
            <% end %>
        </div>
        <div class="col-md-7">
          <div class="card-body">
            <h5 class="card-title"><%= @review.item.name %></h5>
            <h5 class="card-text mt-5"><%= @review.item.price.to_s(:delimited) %>円</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4">
      <%= link_to "#", class: "btn btn-primary", data: { toggle: "collapse", target: "#captionCollapse" } do %>
        説明を読む
      <% end %>
    </div>
    <div class="collapse" id="captionCollapse">
      <small><%= @review.item.caption %></small>
    </div>

    <h4>レビュー</h4>

    <%= form_with model: @review do |f| %>
      <div class="form-group">
        <%= f.text_area :comment, rows: 3, class: "form-control", placeholder: "コメントを入力してください" %>
      </div>

      <%= render 'items/static_rate', review: @review %>

      <div class="form-group mt-4">
        <%= f.submit '保存', class: "btn btn-primary" %>
        <%= link_to "削除", review_path(@review.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
      </div>
    <% end %>

    <%= render 'reviews/review_comment', review: @review, review_comments: @review_comments, review_comment: @review_comment %>

  </div>
</div>

app/views/reviews/index.html.erb
<div class="container-fluid mt-4">
  <div class="row">
    <div class="col px-5">
      <h4>レビュー一覧</h4>
      <p>
        <%= link_to '新しい順', reviews_path(latest: "true") %>
        |<%= link_to '古い順', reviews_path(old: "true") %>
        |<%= link_to '評価の高い順', reviews_path(star_count: "true") %>
        <!--|<%= link_to 'いいねの多い順', reviews_path(favorite_reviews_count: "true") %>-->
      </p>

      <%= form_with(url: reviews_path, method: :get, class: "form-inline") do %>
        <div class="form-group">
          <%= text_field_tag(:search_word, params[:search_word], class: "form-control", placeholder: "キーワードで検索") %>
        </div>
        <%= submit_tag("検索", class: "btn btn-primary ml-2") %>
      <% end %>

      <%= render 'reviews/review_index', reviews: @reviews %>

    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="container my-4">
  <div class="row">
    <div class="col-md-4">
      <%= render 'items/search_genre' %>
    </div>

    <div class="col-md-8">
      <h3>レビュー詳細</h3>

      <div class="card mb-3 mt-4">
        <div class="row g-0">
          <div class="col-md-4 m-3">
            <%= link_to item_path(@review) do %>
              <% images = JSON.parse(@review.item.image_url) %>
              <%= image_tag images.first, style: "width: 100%;" %>
            <% end %>
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <h5 class="card-title"><%= @review.item.name %></h5>
              <h5 class="card-text mt-5"><%= @review.item.price.to_s(:delimited) %>円</h5>
            </div>
          </div>
        </div>
      </div>

      <div class="my-4">
        <%= link_to "#", class: "btn btn-primary", data: { toggle: "collapse", target: "#captionCollapse" } do %>
          説明を読む
        <% end %>
      </div>

      <div class="collapse" id="captionCollapse">
        <small><%= @review.item.caption %></small>
      </div>

      <div class="mt-4">
        <h4 class="mb-4">レビュー(投稿者: <%= link_to @review.user.name, user_path(@review.user) %>)</h4>

        <%= render 'items/static_rate', review: @review %>

        <div class="my-4">
          <p><%= @review.comment %></p>
        </div>

        <div class=<%= "favorite-" + @review.id.to_s %> >
          <%= render "favorite_reviews/btn", review: @review %>
        </div>

        <div class="row mt-4">
          <div class="col">
            <% if current_user.id == @review.user_id %>
              <%= link_to "編集", edit_review_path(@review.id), class: "btn btn-success mr-2" %>
              <%= link_to "削除", review_path(@review.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
            <% end %>
          </div>
        </div>

        <% if current_user.admin? %>
          <!-- 管理者の場合のみ表示 -->
          <div class="admin-controls my-3">
            <% if @review.is_active %>
              <%= link_to "レビューを無効にする", review_path(@review, review: { is_active: false }), method: :put, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "レビューを有効にする", review_path(@review, review: { is_active: true }), method: :put, class: "btn btn-success" %>
            <% end %>
          </div>
        <% end %>

        <%= render 'reviews/review_comment', review: @review, review_comments: @review_comments, review_comment: @review_comment %>

      </div>
    </div>
  </div>
</div>