config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'items#index'

  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete 'users/unsubscribe/:id' => 'users#unsubscribe', as: 'users_unsubscribe'

  get 'items/search', to: 'items#search', as: 'search_items'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch 'user_status' # ユーザーステータスの更新
    end
  end

  resources :items, only: [:index, :show] do
    resource :favorite_items, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :tags, only: [:index, :create, :edit, :update, :destroy]

  resources :reviews do
    resource :favorite_reviews, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
  <footer class="w-100 bg-white">
    <div class="container">
      <div class="text-center text-muted py-3">
        © 2023 GAME JOY

        <%= link_to("Rakuten Web Service Center", {url: "https://webservice.rakuten.co.jp/", target: "_blank"}) do %>
          <%= image_tag "https://webservice.rakuten.co.jp/img/credit/200709/credit_22121.gif", border: 0, alt: "Rakuten Web Service Center", title: "Rakuten Web Service Center", width: 221, height: 21 %>
        <% end %>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="col-2 text-right">
        <h1 class="mb-0"><a class="navbar-brand text-dark" href="/"><img src="<%= asset_path('hlogo.png') %>", style="height:80px"></a></h1>
      </div>
      <h3 class="navbar-brand text-center m-0" href="/">GAME JOY!</h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <!--ユーザーがログインしたら-->
            <li>
              <%=  link_to root_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-magnifying-glass"></i> Search
              <% end %>
            </li>
            <li>
              <%=  link_to reviews_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-ranking-star"></i> Reviews
              <% end %>
            </li>
            <li>
              <%=  link_to  user_path(current_user), class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user"></i> My page
              <% end %>
            </li>

            <% if current_user.admin? %>
              <!--admin ユーザーの場合に表示するメニュー -->
              <li>
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-users" style="color: red;"></i> <span style="color: red;">Users</span>
                <% end %>
              </li>
              <li>
                <%= link_to genres_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-cog" style="color: red;"></i> <span style="color: red;">Genres</span>
                <% end %>
              </li>
              <li>
                <%= link_to tags_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-cog" style="color: red;"></i> <span style="color: red;">Tags</span>
                <% end %>
              </li>
            <% end %>

            <li>
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Logout
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign Up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Login
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamejoy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400;500;700;900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', 'signup',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/09e39a869e.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <% flash.each do |key, value| %>
        <div class="flash-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>